---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiservice
  namespace: food-delivery-nmsp
  labels:
    razee/watch-resource: detail
spec:
  selector:
    matchLabels:
      name: apiservice
  replicas: 1
  template:
    metadata:
      labels:
        name: apiservice
    spec:
      containers:
        - image: us.icr.io/vpc-demo-alex/api:3
          name: apiservice
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: STATUS_SERVICE
              value: 'http://status:8080'
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: KAFKA_SECURITY_PROTOCOL
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: KAFKA_SECURITY_PROTOCOL
            - name: KAFKA_SASL_MECHANISMS
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: KAFKA_SASL_MECHANISMS
            - name:  KAFKA_SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key:  KAFKA_SASL_USERNAME
            - name:  KAFKA_SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: KAFKA_SASL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: apiservice
  namespace: food-delivery-nmsp
  labels:
    razee/watch-resource: detail
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: apiservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: courier
  namespace: food-delivery-nmsp
  labels:
    razee/watch-resource: detail
spec:
  selector:
    matchLabels:
      name: courier
  replicas: 1
  template:
    metadata:
      labels:
        name: courier
    spec:
      containers:
        - image: us.icr.io/vpc-demo-alex/courier:3
          imagePullPolicy: Always
          name: courier
          env:
            - name: MONGODB_REPLICA_HOSTNAMES
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_REPLICA_HOSTNAMES
            - name: MONGODB_REPLICA_SET
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_REPLICA_SET
            - name: MONGODB_DBNAME
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_DBNAME
            - name: MONGODB_AUTH_DBNAME
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_AUTH_DBNAME
            - name: MONGODB_CA_PATH
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_CA_PATH
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_USER
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_PASSWORD
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: KAFKA_SECURITY_PROTOCOL
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: KAFKA_SECURITY_PROTOCOL
            - name: KAFKA_SASL_MECHANISMS
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: KAFKA_SASL_MECHANISMS
            - name:  KAFKA_SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key:  KAFKA_SASL_USERNAME
            - name:  KAFKA_SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: KAFKA_SASL_PASSWORD
          volumeMounts:
            - name: icd-cert
              mountPath: /home/node/app/icd.pem
              subPath: icd.pem
              readOnly: true
      volumes:
        - name: icd-cert
          secret:
            secretName: icd-cert
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitchen
  namespace: food-delivery-nmsp
  labels:
    razee/watch-resource: detail
spec:
  selector:
    matchLabels:
      name: kitchen
  replicas: 1
  template:
    metadata:
      labels:
        name: kitchen
    spec:
      containers:
        - name: kitchen
          image: us.icr.io/vpc-demo-alex/kitchen:3
          imagePullPolicy: Always
          env:
            - name: MONGODB_REPLICA_HOSTNAMES
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_REPLICA_HOSTNAMES
            - name: MONGODB_REPLICA_SET
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_REPLICA_SET
            - name: MONGODB_DBNAME
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_DBNAME
            - name: MONGODB_AUTH_DBNAME
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_AUTH_DBNAME
            - name: MONGODB_CA_PATH
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_CA_PATH
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_USER
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_PASSWORD
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: KAFKA_SECURITY_PROTOCOL
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: KAFKA_SECURITY_PROTOCOL
            - name: KAFKA_SASL_MECHANISMS
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: KAFKA_SASL_MECHANISMS
            - name:  KAFKA_SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key:  KAFKA_SASL_USERNAME
            - name:  KAFKA_SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: KAFKA_SASL_PASSWORD
          volumeMounts:
            - name: icd-cert
              mountPath: /home/node/app/icd.pem
              subPath: icd.pem
              readOnly: true
      volumes:
        - name: icd-cert
          secret:
            secretName: icd-cert
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: food-delivery-nmsp
  labels:
    razee/watch-resource: detail
spec:
  selector:
    matchLabels:
      name: orders
  replicas: 1
  template:
    metadata:
      labels:
        name: orders
    spec:
      containers:
        - image: us.icr.io/vpc-demo-alex/order:3
          imagePullPolicy: Always
          name: orders
          env:
            - name: MONGODB_REPLICA_HOSTNAMES
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_REPLICA_HOSTNAMES
            - name: MONGODB_REPLICA_SET
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_REPLICA_SET
            - name: MONGODB_DBNAME
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_DBNAME
            - name: MONGODB_AUTH_DBNAME
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_AUTH_DBNAME
            - name: MONGODB_CA_PATH
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_CA_PATH
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_USER
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_PASSWORD
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: KAFKA_SECURITY_PROTOCOL
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: KAFKA_SECURITY_PROTOCOL
            - name: KAFKA_SASL_MECHANISMS
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: KAFKA_SASL_MECHANISMS
            - name:  KAFKA_SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key:  KAFKA_SASL_USERNAME
            - name:  KAFKA_SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: KAFKA_SASL_PASSWORD
          volumeMounts:
            - name: icd-cert
              mountPath: /home/node/app/icd.pem
              subPath: icd.pem
              readOnly: true
      volumes:
        - name: icd-cert
          secret:
            secretName: icd-cert
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podconsumerdata
  namespace: food-delivery-nmsp
  labels:
    razee/watch-resource: detail
spec:
  selector:
    matchLabels:
      name: podconsumerdata
  replicas: 1
  template:
    metadata:
      labels:
        name: podconsumerdata
    spec:
      serviceAccountName: default
      imagePullSecrets:
        - name: all-icr-io
      containers:
        - image: us.icr.io/vpc-demo-alex/consumerdata:3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          name: podconsumerdata
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: podconsumerdata
  namespace: food-delivery-nmsp
  labels:
    razee/watch-resource: detail
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: podconsumerdata
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtimedata
  namespace: food-delivery-nmsp
  labels:
    razee/watch-resource: detail
spec:
  selector:
    matchLabels:
      name: realtimedata
  replicas: 1
  template:
    metadata:
      labels:
        name: realtimedata
    spec:
      imagePullSecrets:
        - name: all-icr-io
      containers:
        - image: us.icr.io/vpc-demo-alex/realtimedata:3
          imagePullPolicy: Always
          name: realtimedata
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: KAFKA_SECURITY_PROTOCOL
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: KAFKA_SECURITY_PROTOCOL
            - name: KAFKA_SASL_MECHANISMS
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: KAFKA_SASL_MECHANISMS
            - name:  KAFKA_SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key:  KAFKA_SASL_USERNAME
            - name:  KAFKA_SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: KAFKA_SASL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: realtimedata
  namespace: food-delivery-nmsp
  labels:
    razee/watch-resource: detail
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: realtimedata
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: status
  namespace: food-delivery-nmsp
  labels:
    razee/watch-resource: detail
spec:
  selector:
    matchLabels:
      name: status
  replicas: 1
  template:
    metadata:
      labels:
        name: status
    spec:
      containers:
        - image: us.icr.io/vpc-demo-alex/status:3
          imagePullPolicy: Always
          name: status
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_URL
              value: '693e81c7-f7ba-4235-9817-8b008b66ae17.c7e0lq3d0hm8lbg600bg.databases.appdomain.cloud'
            - name: REDIS_PORT
              value: '31489'
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: KAFKA_SECURITY_PROTOCOL
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: KAFKA_SECURITY_PROTOCOL
            - name: KAFKA_SASL_MECHANISMS
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: KAFKA_SASL_MECHANISMS
            - name:  KAFKA_SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key:  KAFKA_SASL_USERNAME
            - name:  KAFKA_SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: KAFKA_SASL_PASSWORD
          volumeMounts:
            - name: redis-cert
              mountPath: /usr/src/app/redis.pem
              subPath: redis.pem
              readOnly: true
      volumes:
        - name: redis-cert
          secret:
            secretName: redis-cert
---
apiVersion: v1
kind: Service
metadata:
  name: status
  namespace: food-delivery-nmsp
  labels:
    razee/watch-resource: detail
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: status
