apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-food-ingress
spec:
  rules:
  - host: example-food.myvpc-cluster-755191-c4e2224501d69c42822b4ac13e4ce286-0000.us-south.containers.appdomain.cloud 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: example-food
            port:
              number: 8090
      - path: /createOrder
        pathType: Prefix
        backend:
          service:
            name: apiservice
            port:
              number: 8080
      - path: /status
        pathType: Prefix
        backend:
          service:
            name: apiservice
            port:
              number: 8080
      - path: /restaurants
        pathType: Prefix
        backend:
          service:
            name: apiservice
            port:
              number: 8080
      - path: /user
        pathType: Prefix
        backend:
          service:
            name: apiservice
            port:
              number: 8080
      - path: /events
        pathType: Prefix
        backend:
          service:
            name: realtimedata
            port:
              number: 8080
      - path: /consumers
        pathType: Prefix
        backend:
          service:
            name: podconsumerdata
            port:
              number: 8080
